<?php

define("DEVELOPMENT", FALSE);
define("FUNCTIONS", "./functions/");
define("SIMPLE_PAY_KEY", "---------------------------");
define("SIMPLE_PAY_MERCHANT", "S------");

define("DATABASE_ADDR", "mysql56");
define("URL", "http://tag.mrlsz.hu");
define("DATABASE_NAME", "tagmrlszweb_tagmrlszhu");
define("DATABASE_USER", "tagmrlszweb_tagmrlszhu");
define("DATABASE_PASSWORD", "X73jhfSJrt3D");
define("SMTP_USER", "tagmrlszweb");
define("SMTP_PASSWD", "KKieAM7rDGhKKj");
define("TMP_DIR", "../tmp/");
define("SZAMLAZZ_ENABLED", false);

define("COMPANY_NAME", "MRLSz");
define("COMPANY_LONG_NAME", "Magyar Repülő Szövetség");
define("COMPANY_LOGO", 'http://modellsport.hu/sites/default/files/mmsz_logo_regi_orig.png');
